name: flutter_extensions
description: "A comprehensive collection of Dart and Flutter extensions to simplify and enhance your development experience."
version: 1.0.0
homepage: https://github.com/eliseyOzerov/flutter_extensions

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter